apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deploy-toolchain-member-operator
objects:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: toolchain-member-operator
  spec:
    targetNamespaces:
    - ${NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: toolchain-member-operator
  spec:
    channel: ${CHANNEL}
    installPlanApproval: Automatic
    name: toolchain-member-operator
    source: toolchain-member-operator
    sourceNamespace: ${NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: toolchain-member-operator
  spec:
    sourceType: grpc
    image: ${IMAGE_NAME}
    displayName: Hosted Toolchain Operators
parameters:
- name: NAMESPACE
  value: toolchain-member-operator
- name: IMAGE_NAME
  value: toolchain-member-operator-index
- name: CHANNEL
  value: app-sre-staging
