name: operator-cd
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'

jobs:
  binary:
    name: Build & push a new version of operator binary

    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles ('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      env:
        GOPATH: /tmp/go
      run: |
        make build

    - name: Short sha
      uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7

    - name: Build the operator image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
#        image: quay.io/${{ github.repository }}
        image: ${{ github.event.repository.name }}
        tags: ${{ steps.short-sha.outputs.sha }}
        dockerfiles: |
          ./build/Dockerfile


    - name: Build the webhook image
      id: build-image-webhook
      uses: redhat-actions/buildah-build@v2
      with:
        #        image: quay.io/${{ github.repository }}
        image: ${{ github.event.repository.name }}-webhook
        tags: ${{ steps.short-sha.outputs.sha }}
        dockerfiles: |
          ./build/Dockerfile.webhook

    - name: Push To Quay
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
#        registry: quay.io/${{ github.repository }}
        registry: quay.io/matousjobanek/
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Push To Quay webhook
      id: push-to-quay-webhook
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image-webhook.outputs.image }}
        tags: ${{ steps.build-image-webhook.outputs.tags }}
        #        registry: quay.io/${{ github.repository }}
        registry: quay.io/matousjobanek/
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Use the image
      run: echo "New image has been pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"


  bundle:
    name: Build & push a new version of operator bundle and update index image

    runs-on: ubuntu-latest
    needs: binary

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: generate manifests
      env:
        OPERATOR_SDK_VERSION: v0.19.2
      run: |
        set -e
        # download, verify and install operator-sdk
        curl -L -s https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu -o operator-sdk \
          && curl -L -s https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu.asc -o operator-sdk.asc \
          && gpg --keyserver keyserver.ubuntu.com --recv-key 9AF46519 \
          && gpg --verify operator-sdk.asc \
          && chmod +x operator-sdk \
          && sudo cp operator-sdk /usr/bin/operator-sdk \
          && rm operator-sdk \
          && operator-sdk version

        pip3 install yq

        make generate-cd-release-manifests QUAY_NAMESPACE=matousjobanek


